env:
  global:
    - CC_TEST_REPORTER_ID=118d7588cc038423ce1317f9c83ab1bef131ebbce0350d2f17dcb2c28927b34c
language: node_js
node_js:
  - "10"
before_install:
  - npm install -g greenkeeper-lockfile lerna
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - greenkeeper-lockfile-update
script:
  - yarn bootstrap
  - yarn quality:lint
  - yarn build
  - yarn test:coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: raziel@binarygenetics.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    branch: master
