version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - run:
          name: 'Version check'
          command: |
            node --version
            yarn --version
      - checkout
      - run:
          name: 'Tools'
          command: npm install -g lerna
      - run:
          name: 'Dependencies'
          command: yarn bootstrap
      - run:
          name: 'Lint'
          command: yarn quality:lint
      - run:
          name: 'Build'
          command: yarn build
      - run:
          name: 'Unit tests'
          command: yarn test:coverage
